### ISSUE TITLE
Segfaults on on_disconnect.

### ISSUE THREAD

**Issue by krisppurg** [krisppurg/dimscord#30]
This occurs when s.connection == nil.

**Comment by ire4ever1190** [comment]
in case anyone is having the issue like me, a hacky solution until it is solved is to just use the on_disconnect event
```nim
discord.events.on_disconnect = proc (s: Shard) {.async.} =
    echo("You have been disconnected")
```

**Comment by krisppurg** [comment]
Have you tried that hobble?

**Comment by ire4ever1190** [comment]
Using it in doccat, hasn't crashed when it usually would after a few hours
