### ISSUE TITLE
Use treeform's jsony for rewriting objects

### ISSUE THREAD

**Issue by krisppurg** [krisppurg/dimscord#32]
If a field is null or simply doesn't exist it will get an internal fatal crash. However we could actually use marshal for this since, it does not crash.

**Comment by Yardanico** [comment]
Please don't - marshal uses Nim RTTI and it makes binaries larger :) Maybe look into nim-json-serialization by Status instead?

**Comment by krisppurg** [comment]
Okay.

**Comment by krisppurg** [comment]
Renamed title.

**Comment by krisppurg** [comment]
So, since the files are starting to get bigger as Discord's API starts to expand more, I might as well use that serialization and modify it in the future.

**Comment by krisppurg** [comment]
Closing this, as not much activity.

**Comment by krisppurg** [comment]
Currently rewriting objects with jsony, making dimscord run more efficiently and to minimise file size of objects

**Comment by krisppurg** [comment]
I believe all of the objects are all now replaced with jsony.
