### ISSUE TITLE
[BUG] `attempting to call undeclared routine: 'getChannel'` on execution

### ISSUE THREAD

**Issue by rikusen0335** [krisppurg/dimscord#54]
**Describe the bug**
Got an error: `attempting to call undeclared routine: 'getChannel'` on executing program with dimscmd.

**Steps to reproduce**
Copy-paste https://github.com/krisppurg/dimscord README sample, and just add `dimscmd` to import

**Expected behavior**
Actually runs

**Screenshots**

**Additional context**
`dimscord` -> 1.2.5
`dimscmd` -> 1.1.2
`nim` -> 1.4.8

**Comment by ire4ever1190** [comment]
author of dimscmd here
could you uninstall dimscord with `nimble uninstall dimscord` and then install the bleeding edge version with `nimble install dimscord@#head`?

**Comment by rikusen0335** [comment]
@ire4ever1190 Thanks for quick reply!
Okay, lemme try it.

**Comment by rikusen0335** [comment]
I think it has fixed. Thank you for helping and sorry for bothers you.

**Comment by ire4ever1190** [comment]
Happy to help
if there are anymore issues you can always create an issue on the dimscmd page or ask on the discord

**Comment by krisppurg** [comment]
Also if that error comes from a third party dsl library (like dimscmd), you could either make a PR or Issue to dimscmd.

Anyways, hobble I think you might either make a seperate getChannel for the time being using `api.request(...)`, since that is also public.

**Comment by krisppurg** [comment]
By hobble, I mean @ire4ever1190 my bad lol.

**Comment by ire4ever1190** [comment]
my fault for having different names lol
But I don't know how this issue popped up seeing as I require a specific commit in dimscmd that contains the newer fixes I need
Think nim doesn't do the same version resolution when you run the file directly instead of using nimble
