### ISSUE TITLE
bulkDeleteMessages doesnt work

### ISSUE THREAD

**Issue by Vaipex** [krisppurg/dimscord#76]
I tried dimscord today and wanted to use the bulkDeleteMessages proc.
I always get this error when I try to compile it.
`nimble/pkgs/dimscord-1.3.0/dimscord/restapi/guild.nim(90, 25) Error: expression 'none seq[Channel]' has no type (or is ambiguous)`

This is my code:
```
let test = await discord.api.bulkDeleteMessages(chid, msgseq)
echo resptest
```

**Comment by krisppurg** [comment]
The line that it points to is at createGuild proc, does it error if you remove the code?

Try doing `nimble install dimscord@#head` for the fix, since I believe this error occurs when `--threads:on`

**Comment by krisppurg** [comment]
Did you import asyncdispatch?

**Comment by Vaipex** [comment]
yes

**Comment by krisppurg** [comment]
For messageCreate proc, could you remove the `{.event(discord).}` pragma and leave as something like this?
```nim
proc messageCreate(s: Shard, m: Message) {.async.} =
  ...

discord.events.messageCreate = messageCreate
```
This will make the error a bit more easier to understand.

**Comment by Vaipex** [comment]
Looks like its the same error

```
template/generic instantiation of `async` from here
```
```
Error: expression '
var internalTmpFuture`gensym21: FutureBase = bulkDeleteMessages(discord.api,
    "123", @["123"], "")
yield internalTmpFuture`gensym21
read(cast[typeof(bulkDeleteMessages(discord.api, "123", @["123"], ""))](internalTmpFuture`gensym21))' has no type (or is ambiguous)
```

**Comment by krisppurg** [comment]
Hmm, the code looks fine to me. Try sending your code that isn't exactly simplified.

**Comment by Vaipex** [comment]
I found the issue, bulkDeleteMessages doesnt return anything. `await discord.api.bulkDeleteMessages("123", @["123"])` works just fine.
Thank you for your time!
