### ISSUE TITLE
Error: unhandled exception: value out of range: 18 notin 0 .. 14

### ISSUE THREAD

**Issue by GeeLeonidas** [krisppurg/dimscord#97]
## Description
I've recently noticed that my bot crashed every time it was trying to play audio, apparently a new voice op code is being given to be handled and it is not defined in the VoiceOp enum. Error message is the one in the title.
Traceback points to `dimscord-#head/dimscord/voice.nim(398) handleSocketMessageIter`: https://github.com/krisppurg/dimscord/blob/41eea2aeafe2f6ea3ab861efa8e1d4ddbf214dc1/dimscord/voice.nim#L398

## Temporary solution
Quite inelegant and probably troublesome, but hey it works™ (i.e. stops crashing):
```nim
const VoiceOpRange = VoiceOp.low.ord .. VoiceOp.high.ord
let
  dataOp = data["op"].num
  dataVoiceOp = if dataOp in VoiceOpRange: VoiceOp(dataOp) else: Something
case dataVoiceOp
of # ...
```

## How to reproduce
Using `examples/voice.nim` and `dimscord#head` should suffice (https://github.com/krisppurg/dimscord/blob/41eea2aeafe2f6ea3ab861efa8e1d4ddbf214dc1/examples/voice.nim)

**Comment by krisppurg** [comment]
Think it would be better to simply change VoiceOp to const. Will fix in a day or two.

**Comment by ire4ever1190** [comment]
Think the solution given is best

Add an `Unknown` value to the enum which is used when the opcode isn't in the range of `FirstGoodValue..LastValue`

Switching to const would remove some type safety and make it a bit more unclean imo

**Comment by krisppurg** [comment]
The issue is fixed, should [be fine now](https://github.com/krisppurg/dimscord/commit/d62471c707e1118ef9f957b985f6d5e3dfd275e8).
